[[redirects]]
  from = "/data/*"
  to = "https://youthful-mahavira-a88750.netlify.com/data/:splat"
  status = 200
  force = true

  from = "/product/*"
  to = "https://xenodochial-tereshkova-b37118.netlify.com/product/:splat"
  status = 200
  force = true